# Generated by Django 3.1.1 on 2020-10-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'pin')},
        ),
    ]
